version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API-Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: UI-Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env